### ISSUE TITLE
memory increasing

### ISSUE THREAD

**Issue by Dorothy-2016** [LinHuican/stereo_dso_ros#4]
when you run the stereo dso with your own camera, does the memory increased all the time? I tried it with my own camera, it seemed like this.

**Comment by TengFeiHan0** [comment]
Did you solve this problem? I got the same issue.@Dorothy-2016

**Comment by LinHuican** [comment]
@Dorothy-2016 @TengFeiHan0 
Fix the bug of memory increase 
https://github.com/LinHuican/stereo_dso_ros/commit/95d1b2db0f45274191876126bba8d747357f153a
