### ISSUE TITLE
Maybe you should add something in CMakelists.txt ?

### ISSUE THREAD

**Issue by AndroidStudio2017** [LinHuican/stereo_dso_ros#6]
Hi, I'm trying to run a SLAM with KITTI recently. First, I am very grateful for the work you have done, but I find some problems.

When I downloaded code and tried to complie it with 'catkin_make', there are something wrong.

`[100%] Linking CXX executable /home/johnson/catkin_ws/devel/lib/stereo_dso_ros/stero_dso_ros
/home/johnson/stereo_dso/build/lib/libdso.a(ImageDisplay_OpenCV.cpp.o): In function `dso::IOWrap::waitKey(int)':
/home/johnson/stereo_dso/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp:185: undefined reference to `cv::waitKey(int)'
/home/johnson/stereo_dso/build/lib/libdso.a(ImageDisplay_OpenCV.cpp.o): In function `dso::IOWrap::closeAllWindows()':
/home/johnson/stereo_dso/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp:192: undefined reference to `cv::destroyAllWindows()'
/home/johnson/stereo_dso/build/lib/libdso.a(ImageDisplay_OpenCV.cpp.o): In function `dso::IOWrap::displayImage(char const*, cv::Mat const&, bool)':
/home/johnson/stereo_dso/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp:63: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
/home/johnson/stereo_dso/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp:58: undefined reference to `cv::namedWindow(cv::String const&, int)'
/home/johnson/stereo_dso/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp:59: undefined reference to `cv::resizeWindow(cv::String const&, int, int)'
`

I think this is because of a lack of OpenCV libs. I add 'find_package(OpenCV REQUIRED)' to CMakelists.txt and it works.

This is just a hint. Hope that you work will be smooth later.

**Comment by robin-shaun** [comment]
Oh, I have met the same problem, and your advice works, thanks!

**Comment by LinHuican** [comment]
Sorry, I was busy with other things before. The reply was too late.
You are right, my mistake.
I added find_package (OpenCV REQUIRED).
Also, I added set (OpenCV_DIR "/ some_path_to / OpenCV /"), but this is not required, it depends.
Thank you, best wishes.
